version: "3.8"

services:
  service-wp-nginx:
    image: nginx:0.8.5.2
    stdin_open: true
    container_name: wp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - C:\DockerVolumes\wp-nginx:/var/www/wordpress

  service-wp-mysql:
    image: mysql:latest
    stdin_open: true
    container_name: wp-mysql
    ports:
      - "3306:3306"
    volumes:
      - C:\DockerVolumes\wp-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db-wordpress
      MYSQL_USER: db-wordpress
      MYSQL_PASSWORD: db-wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: db-wordpress

  service-wp-mysql-phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: wp-mysql-phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: wp-mysql
    depends_on:
      - service-wp-mysql
