FROM mysql:latest

# Set the MySQL root password (change 'your_root_password' to your desired password)
ENV MYSQL_ROOT_PASSWORD=mysql-root

# (Optional) Set a database name, user, and password (change 'your_database', 'your_user', and 'your_password' respectively)
ENV MYSQL_DATABASE=db-wordpress
ENV MYSQL_USER=wpadmin
ENV MYSQL_PASSWORD=wpadmin